name: resmpk
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  crypto: ^3.0.3
  shimmer: ^3.0.0
  intl: ^0.18.1
  top_snackbar_flutter: ^3.1.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  hive: ^2.2.3
  path_provider: ^2.1.2
  auto_route: ^7.9.2
  equatable: ^2.0.5
  provider: ^6.1.2
  bloc: ^8.1.4
  flutter_native_splash: ^2.3.11
  get_it: ^7.6.7
  injectable: ^2.3.5
  flutter_bloc: ^8.1.5
  flutter_localization: ^0.2.0
  hive_generator: ^2.0.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  dio: ^4.0.6
  geolocator: ^11.0.0
  flutter_map_marker_cluster: ^1.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  injectable_generator: ^2.4.2
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
  fonts:
    - family: Poppins-Reg
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
    - family: Poppins-Bol
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
    - family: Poppins-Med
      fonts:
        - asset: assets/fonts/poppins/Poppins-Medium.ttf

flutter_native_splash:
  color: "#ffffff"
  image: assets/icon.png
  branding: assets/icon.png
  color_dark: "#ffffff"
  image_dark: assets/icon.png
  branding_dark: assets/icon.png
  android_12:
    image: assets/icon.png
    icon_background_color: "#ffffff"
    image_dark: assets/icon.png
    icon_background_color_dark: "#ffffff"

  web: false
